### ISSUE TITLE
Load LDraw parts from ZIP packages directly

### ISSUE THREAD

**Issue by Symbian9** [trevorsandy/blenderldrawrender#1]
Is it possible add option for load LDraw parts directly from ZIP packages without unpacking it to local drive? (`complete.zip`, `ldrawunf.zip`, `{other-3rd-party-parts}.zip`, etc.)

- https://github.com/Symbian9/AWESOME-LDraw#ldraw-official-and-unofficial-parts

### RELATED ISSUES

- https://github.com/TobyLobster/ImportLDraw/issues/37

**Comment by trevorsandy** [comment]
Yes  it is.

Cheers,

**Comment by trevorsandy** [comment]
Implemented - See  [Auto detect and load LDraw parts archive (.zip) files](https://github.com/trevorsandy/blenderldrawrender/commit/7d099c53f6e5eaf8544463a1c7afa5b90a211259)

This enhancement allows the addon to automatically detect and parse .zip files in the specified LDraw path. When a zip file is detected, if the archive contains 'ldraw/LDConfig.ldr' it is deemed to be an official LDraw library archive. Other archive files are checked for the occurrence of files with 'dat', 'ldr', and 'mpd' extensions. If such file is encountered in the archive, it is automatically added as an unofficial LDraw library archive.

The behaviour described above allow for a single 'official' archive and any number of subsequent 'unofficial' archives to be placed in the specified LDraw library path. There is no check to control if multiple archive files containing 'ldraw/LDconfig.ldr' exists at the library path. In this situation. the unique files among the similar archives and the first read similar files will persist. Content from the official archive library will be checked before those in the unofficial libraries.

#### Performance Note
To optimize performance, archive libraries are read before the initial model file load. Library contents are placed in either an official or unofficial library cache in memory. This step adds a unique delay on the initial model load time when compared to loading model files from disc - loading subsequent models in the same session is not impacted. For example, a model that takes 0.70 second to initially load will take 3.1 seconds - when loading both the official and unofficial LDraw archive libraries. However, it is important to note the entire delta (2.3 seconds) is attributed to the library load. This means that scaling the model size and complexity will have no material impact on the overall load time beyond the initial 3-second delay. Moreover, bigger models could actually see an improvement in the load time when using the archive cache as it is considerably faster to retrieve part data from the memory cache than from the disc. This improvement will be seen when the model file size and complexity is such that the time to load all its respective models and submodels exceed the 3-second penalty incurred when loading ing the archive libraries. Lastly, the 3-second penalty is variable against the size and number of archive files being loaded. The optimum configuration would be to consolidate your 'custom' parts etc. within a single unofficial archive library.

Cheers,
