### ISSUE TITLE
Add HOWTO.md

### ISSUE THREAD

**Issue by ghost** [trevorsandy/blenderldrawrender#2]
> This addon was designed to provide LPub3D an autonomous module enabling the integrated import and render of LDraw LEGO® models using Blender™. However, it can be executed directly from the Blender GUI, CLI or your operating system command console.

Please, add `HOWTO.md` docs with instructions on how to use it:

- System requirements / Needed software list.
- How to execute it from the Blender GUI.
- How to execute it from CLI (Blender CLI?).
- How to use it throw operating system command console/terminal.

### REFERENCE

- https://github.com/Symbian9/AWESOME-LDraw#other-software

**Comment by trevorsandy** [comment]
Please see the README.md

Cheers,
